groups:
    - developer
    - media

attributes:
    osxdefaults:
        finder:
            finder_set_preferred_view_style: Nlsv
        terminal:
            profile: Solarized-Dark-ansi
        computername: MBP

    git:
        name: Peter Liljenberg
        email: pliljenberg@gmail.com
    authorization:
        sudo:
            users:
                - peterl
            passwordless: true
            include_sudoers_d: true
