groups:
    - developer
    - media
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name

attributes:
    osxdefaults:
        computername: MBP

    git:
        name: Peter Liljenberg
        email: pliljenberg@gmail.com
    authorization:
        sudo:
            users:
                - peterl
            passwordless: true
            include_sudoers_d: true
