groups:
    - developer
    - media
    - amazon
    - speedledger

attributes:
    osxdefaults:
        finder:
            finder_set_preferred_view_style: Nlsv
        terminal:
            profile: Solarized-Dark-ansi
        computername: Axiom

    git:
        name: Peter Liljenberg
        email: pl@speedledger.se
    authorization:
        sudo:
            users:
                - pl
            passwordless: true
            include_sudoers_d: true
